### ISSUE TITLE
umi-ui 安装区块失败

### ISSUE THREAD

**Issue by zhangkailikelly** [umijs/umi-ui#117]
{ SyntaxError: This experimental syntax requires enabling the parser plugin: 'optionalChaining' (70:17)
    at Object.raise (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:6344:17)
    at Object.expectPlugin (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:7664:18)
    at Object.parseSubscript (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8448:12)
    at Object.parseSubscript (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:5288:18)
    at Object.parseSubscripts (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8434:19)
    at Object.parseExprSubscripts (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8423:17)
    at Object.parseMaybeUnary (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8393:21)
    at Object.parseMaybeUnary (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:5668:20)
    at Object.parseExprOps (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8280:23)
    at Object.parseMaybeConditional (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8253:23)
    at Object.parseMaybeAssign (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8200:21)
    at Object.parseMaybeAssign (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:5628:20)
    at Object.parseExpression (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:8148:23)
    at Object.parseStatementContent (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:9917:23)
    at Object.parseStatementContent (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:5392:18)
    at Object.parseStatement (/Users/kelly/work/demo/umi3/pro_v4/node_modules/@umijs/block-sdk/node_modules/@babel/parser/lib/index.js:9788:17)
  pos: 1515,
  loc: Position { line: 70, column: 17 },
  missingPlugin: [ 'optionalChaining' ] }

**Comment by G233** [comment]
我也遇到了同样的问题
