### ISSUE TITLE
BUG-打开不正确项目时，umi-ui没法再用

### ISSUE THREAD

**Issue by Gray497** [umijs/umi-ui#31]
## What happens?
如题

## Mini Showcase Repository(REQUIRED)

> Provide a mini GitHub repository which can reproduce the issue.
> Use `yarn create umi` then upload to your GitHub

## How To Reproduce
**Steps to reproduce the behavior:**
1. 打开umi脚手架构建的项目
2.再打开老版本 2.0 umi的项目

**Expected behavior**
1.正常使用
2.

## Context

![image](https://user-images.githubusercontent.com/20183400/76402737-c8adf080-63be-11ea-81d9-fb52ff01957c.png)

umi.20ab616f.js:1 eeeeee 
{title: "依赖文件没找到。", message: "Cannot find module 'umi-plugin-react' from '/Users/guoweipeng/code/maxfaith/miop/miop_ui'", stack: "Error: Cannot find module 'umi-plugin-react' from …a/home/node_modules/@umijs/ui/lib/UmiUI.js:407:7)", actions: Array(2)}
title: "依赖文件没找到。"
message: "Cannot find module 'umi-plugin-react' from '/Users/guoweipeng/code/maxfaith/miop/miop_ui'"
stack: "Error: Cannot find module 'umi-plugin-react' from '/Users/guoweipeng/code/maxfaith/miop/miop_ui'↵    at Function.resolveSync [as sync] (/Users/guoweipeng/code/weya/home/node_modules/resolve/lib/sync.js:81:15)↵    at /Users/guoweipeng/code/weya/home/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:109:29↵    at Array.map (<anonymous>)↵    at getPluginsOrPresets (/Users/guoweipeng/code/weya/home/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:108:99)↵    at resolvePlugins (/Users/guoweipeng/code/weya/home/node_modules/@umijs/core/lib/Service/utils/pluginUtils.js:202:19)↵    at new Service (/Users/guoweipeng/code/weya/home/node_modules/@umijs/core/lib/Service/Service.js:177:59)↵    at new Service (/Users/guoweipeng/code/weya/home/node_modules/umi/lib/ServiceWithBuiltIn.js:50:5)↵    at UmiUI.getService (/Users/guoweipeng/code/weya/home/node_modules/@umijs/ui/lib/UmiUI.js:249:23)↵    at /Users/guoweipeng/code/weya/home/node_modules/@umijs/ui/lib/UmiUI.js:369:40↵    at Generator.next (<anonymous>)↵    at asyncGeneratorStep (/Users/guoweipeng/code/weya/home/node_modules/@umijs/ui/lib/UmiUI.js:212:103)↵    at _next (/Users/guoweipeng/code/weya/home/node_modules/@umijs/ui/lib/UmiUI.js:214:194)↵    at /Users/guoweipeng/code/weya/home/node_modules/@umijs/ui/lib/UmiUI.js:214:364↵    at new Promise (<anonymous>)↵    at /Users/guoweipeng/code/weya/home/node_modules/@umijs/ui/lib/UmiUI.js:214:97↵    at UmiUI.openProject (/Users/guoweipeng/code/weya/home/node_modules/@umijs/ui/lib/UmiUI.js:407:7)"
actions: Array(2)
0: {title: "重新安装依赖", handler: {…}}
1: {title: "返回主页", browserHandler: "BACK_TO_HOME"}

- **Umi Version**:
3.0.7
- **Node Version**:
12.16.1
- **UMI_UI Version**:
2.0.6
- **Platform**:
mac

**Comment by Gray497** [comment]
![image](https://user-images.githubusercontent.com/20183400/76402760-d06d9500-63be-11ea-8131-2100f49b8a43.png)
