### ISSUE TITLE
添加模板时报错，找不到config/config.js

### ISSUE THREAD

**Issue by MakeHui** [umijs/umi-ui#82]
## What happens?

添加模板时报错，找不到`config/config.js`
windows 系统和 wsl2 系统下均是这个错误

## 最小可复现仓库

> 请使用 `yarn create @umijs/umi-app` 创建，并上传到你的 GitHub 仓库
https://github.com/MakeHui/umi-ui-issue

## 复现步骤，错误日志以及相关配置

![image](https://user-images.githubusercontent.com/8622405/86768805-b0a26100-c080-11ea-888e-8a1a92a05ee5.png)
```
Execute task error Error: Error: ENOENT: no such file or directory, open 'config/config.js'
    at E:\Projects\Wogoo\tquestion_admin\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:88:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\Projects\Wogoo\tquestion_admin\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:46:103)
    at _next (E:\Projects\Wogoo\tquestion_admin\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:48:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[Asset Error] Error: Error: ENOENT: no such file or directory, open 'config/config.js'
    at E:\Projects\Wogoo\tquestion_admin\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:88:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\Projects\Wogoo\tquestion_admin\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:46:103)
    at _next (E:\Projects\Wogoo\tquestion_admin\node_modules\@umijs\plugin-ui-blocks\lib\ui\server\core\tasks\gitTasks\write_routes.js:48:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
## 相关环境信息

- **Umi 版本**：
umi@3.2.8
- **Node 版本**：
v12.18.2
- **操作系统**：
版本：windows10 专业版
版本号：2004
操作系统版本：19041.329

**Comment by ycjcl868** [comment]
试了下没问题

**Comment by MakeHui** [comment]
我继续使用 macOS 系统尝试, 结果依旧是这样, 请问处理安装 umi 外还需要额外安装其他的东西吗?

**Comment by MakeHui** [comment]
出现报错的安装方式
```
$ mkdir myapp && cd myapp
$ yarn create @umijs/umi-app
$ yarn
$ yarn add @umijs/preset-ui -D
$ UMI_UI=1 umi dev
```
使用正常的安装方式
```
$ yarn create umi my-app
Select the boilerplate type ant-design-pro
 Be the first to experience the new umi@3 ? Pro V4
  Which language do you want to use? JavaScript
  Do you need all the blocks or a simple scaffold? complete
```
---
> 发现一个新的问题， 如果是通过umi ui 创建的项目安装模板时显示成功，但是控制台提示报错， 并且 路由并没有加入到 config.js 中
>下图中显示的路径也不对，我用umi ui 创建的项目是test，在test里面添加的模板，控制台显示的是 my-app

![image](https://user-images.githubusercontent.com/8622405/87915882-4b4d6780-caa5-11ea-912a-632a5e7b7422.png)
@ycjcl868
